//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthService.Common.Resources.ApiMessagesResource", typeof(ApiMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not fan of this artist now.
        /// </summary>
        internal static string AristFansDelete {
            get {
                return ResourceManager.GetString("AristFansDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have become fan of this artist.
        /// </summary>
        internal static string AristFansSuccessful {
            get {
                return ResourceManager.GetString("AristFansSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already fan of this artist.
        /// </summary>
        internal static string ArtistFanExists {
            get {
                return ResourceManager.GetString("ArtistFanExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtWork rating saved Successfully.
        /// </summary>
        internal static string ArtRatingSavedSuccessful {
            get {
                return ResourceManager.GetString("ArtRatingSavedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtWork rating saved Unsuccessful.
        /// </summary>
        internal static string ArtRatingSavedUnsuccessfull {
            get {
                return ResourceManager.GetString("ArtRatingSavedUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while geting max drop Supply.
        /// </summary>
        internal static string DropSupplyScriptError {
            get {
                return ResourceManager.GetString("DropSupplyScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given email already register.
        /// </summary>
        internal static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occour while sending Email.
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not verified.
        /// </summary>
        internal static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save Email Subscription Data.
        /// </summary>
        internal static string EmailSubscriptionFailed {
            get {
                return ResourceManager.GetString("EmailSubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verified successfully.
        /// </summary>
        internal static string EmailVerified {
            get {
                return ResourceManager.GetString("EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong please try again!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while insert order into DB.
        /// </summary>
        internal static string ErrorOnOrderInsertionDB {
            get {
                return ResourceManager.GetString("ErrorOnOrderInsertionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded login attempts.
        /// </summary>
        internal static string ExceededLoginAttempts {
            get {
                return ResourceManager.GetString("ExceededLoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your provided code has been expired..
        /// </summary>
        internal static string ExpireCode {
            get {
                return ResourceManager.GetString("ExpireCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong on server.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong on server.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code provided.
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is not correct.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Role.
        /// </summary>
        internal static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Invitation link has been expire please resend!.
        /// </summary>
        internal static string InviteUrlExpire {
            get {
                return ResourceManager.GetString("InviteUrlExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successfully.
        /// </summary>
        internal static string Logoutsuccessfully {
            get {
                return ResourceManager.GetString("Logoutsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artist found.
        /// </summary>
        internal static string NoArtistFound {
            get {
                return ResourceManager.GetString("NoArtistFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user profile data found.
        /// </summary>
        internal static string NoUserProfileDataFound {
            get {
                return ResourceManager.GetString("NoUserProfileDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Addition Failed.
        /// </summary>
        internal static string OrderFailed {
            get {
                return ResourceManager.GetString("OrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Order Found.
        /// </summary>
        internal static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order has been created successfully.
        /// </summary>
        internal static string OrderSuccessful {
            get {
                return ResourceManager.GetString("OrderSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while Processing Payment.
        /// </summary>
        internal static string PaymentProcessingError {
            get {
                return ResourceManager.GetString("PaymentProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment made successfully but Error occured while Minting or Order insertion.
        /// </summary>
        internal static string PaymentSucessButErrorInMintingAndOrder {
            get {
                return ResourceManager.GetString("PaymentSucessButErrorInMintingAndOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered successfully.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Already Exist.
        /// </summary>
        internal static string RoleAlreadyExist {
            get {
                return ResourceManager.GetString("RoleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3 Bucket Already Exist.
        /// </summary>
        internal static string S3BucketAlreadyExist {
            get {
                return ResourceManager.GetString("S3BucketAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3 Bucket Not Exist.
        /// </summary>
        internal static string S3BucketNotExist {
            get {
                return ResourceManager.GetString("S3BucketNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Saving NFT Survey Data.
        /// </summary>
        internal static string SaveNFTSurveyDataFailure {
            get {
                return ResourceManager.GetString("SaveNFTSurveyDataFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wong while serializing data..
        /// </summary>
        internal static string SerializtionError {
            get {
                return ResourceManager.GetString("SerializtionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Confirmation.
        /// </summary>
        internal static string TransactionConfrimation {
            get {
                return ResourceManager.GetString("TransactionConfrimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already registered.
        /// </summary>
        internal static string UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email is already Verified.
        /// </summary>
        internal static string UserAlreadyVerified {
            get {
                return ResourceManager.GetString("UserAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is disabled by admin.
        /// </summary>
        internal static string UserDisabledError {
            get {
                return ResourceManager.GetString("UserDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email is already Verified.
        /// </summary>
        internal static string UserEmailAlreadyVerified {
            get {
                return ResourceManager.GetString("UserEmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email not verified please verify and login.
        /// </summary>
        internal static string UserEmailNotVerified {
            get {
                return ResourceManager.GetString("UserEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been logged in successfully.
        /// </summary>
        internal static string UserLoginSucess {
            get {
                return ResourceManager.GetString("UserLoginSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName not available.
        /// </summary>
        internal static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number not verified please verify and login.
        /// </summary>
        internal static string UserPhoneNotVerified {
            get {
                return ResourceManager.GetString("UserPhoneNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while user sign-up.
        /// </summary>
        internal static string UserRegistrationError {
            get {
                return ResourceManager.GetString("UserRegistrationError", resourceCulture);
            }
        }
    }
}
